<?php

namespace App\Http\Controllers;

use App\Setting;
use Auth;

class StaticDataController extends UserController
{

    public function __construct()
    {
        $this->middleware('auth',['except' => ['setting','settings']]);
    }

    public function setting($type){

        $privacy =  "<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App Privacy Statement</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Last Updated: April 2019</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Your privacy is important to us. This privacy statement explains the personal data SWIS App processes, how SWIS App processes it, and for what purposes.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App offers a wide range of experiences leveraging 3</span><span style=\"font-size: 7.199999999999998pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: super; white-space: pre-wrap;\">rd</span><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"> party products to provide the SWIS App experience. &nbsp;References to SWIS App products in this statement include SWIS App services, websites, apps, software, servers, and devices.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Please read the product-specific details in this privacy statement, which provide additional relevant information. This statement applies to the interactions SWIS App has with you and the SWIS App 3</span><span style=\"font-size: 7.199999999999998pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: super; white-space: pre-wrap;\">rd</span><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"> party products listed below, as well as other SWIS App products that display this statement.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Personal data we collect</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App collects data from you, through our interactions with you and through our products. You provide some of this data directly, and we get some of it by collecting data about your interactions, use, and experiences with our 3</span><span style=\"font-size: 7.199999999999998pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: super; white-space: pre-wrap;\">rd</span><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"> party products. The data we collect depends on the context of your interactions with SWIS App and the choices you make, including your settings and the products and features you use. We also obtain data about you from third parties.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You have choices when it comes to the technology you use and the data you share. When we ask you to provide personal data, you can decline. Many of our products require some personal data to provide you with our service. If you choose not to provide data necessary to provide you with a product or feature, you cannot use that product or feature. Likewise, where we need to collect personal data by law or to enter into or carry out a contract with you, and you do not provide the data, we will not be able to enter into the contract; or if this relates to an existing product you&rsquo;re using, we may have to suspend or cancel it. We will notify you if this is the case at the time. Where providing the data is optional, and you choose not to share personal data, features like personalization that use such data will not work for you.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>How we use personal data</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App uses the data we collect to provide you with rich, interactive experiences. In particular, we use data to:</span></p>
<ul style=\"margin-top: 0pt; margin-bottom: 0pt;\">
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Provide our products, which includes updating, securing, and troubleshooting, as well as providing support. It also includes sharing data, when it is required to provide the service or carry out the transactions you request.</span></li>
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Improve and develop our products.</span></li>
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Personalize our products and make recommendations.</span></li>
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Advertise and market to you, which includes sending promotional communications, targeting advertising, and presenting you with relevant offers.</span></li>
</ul>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We also use the data to operate our business, which includes analyzing our performance, meeting our legal obligations, developing our workforce, and doing research.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">In carrying out these purposes, we combine data we collect from different contexts (for example, from your use of two SWIS App products) or obtain from third parties to give you a more seamless, consistent, and personalized experience, to make informed business decisions, and for other legitimate purposes.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\">&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Reasons we share personal data</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We share your personal data with your consent or to complete any transaction or provide any product you have requested or authorized. We also share data with SWIS App-controlled affiliates and subsidiaries; with vendors working on our behalf; when required by law or to respond to legal process; to protect our customers; to protect lives; to maintain the security of our products; and to protect the rights and property of SWIS App and its customers.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>How to access and control your personal data</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You can also make choices about the collection and use of your data by SWIS App. You can control your personal data that SWIS App has obtained, and exercise your data protection rights, by contacting SWIS App or using various tools we provide. In some cases, your ability to access or control your personal data will be limited, as required or permitted by applicable law. </span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Cookies and similar technologies</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Cookies are small text files placed on your device to store data that can be recalled by a web server in the domain that placed the cookie. We use cookies and similar technologies for storing and honoring your preferences and settings, enabling you to sign in, providing interest-based advertising, combating fraud, analyzing how our products perform, and fulfilling other legitimate purposes. SWIS App apps use additional identifiers, such as the advertising ID in Windows described in the Advertising ID section of this privacy statement, for similar purposes.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We also use &ldquo;web beacons&rdquo; to help deliver cookies and gather usage and performance data. Our websites may include web beacons, cookies, or similar technologies from third-party service providers.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You have a variety of tools to control the data collected by cookies, web beacons, and similar technologies. For example, you can use controls in your internet browser to limit how the websites you visit are able to use cookies and to withdraw your consent by clearing or blocking cookies.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Products provided by your organization&mdash;notice to end users</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you use a SWIS App product or use an email address to access SWIS App products and that product or email address was provided by an organization you are affiliated with, such as an employer or school, that organization can:</span></p>
<ul style=\"margin-top: 0pt; margin-bottom: 0pt;\">
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Control and administer your SWIS App product and product account, including controlling privacy-related settings of the product or product account.</span></li>
<li style=\"list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Access and process your data, including the interaction data, diagnostic data, and the contents of your communications and files associated with your SWIS App product and product accounts.</span></li>
</ul>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you lose access to your work or school account (in event of change of employment, for example), you may lose access to products and the content associated with those products, including those you acquired on your own behalf, if you used your work or school account to sign in to such products.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you used a work account, you should direct your privacy inquiries, including any requests to exercise your data protection rights, to your organization&rsquo;s administrator. When you use social features in SWIS App products, other users in your network may see some of your activity. To learn more about the social features and other functionality, please review documentation or help content specific to the SWIS App product. SWIS App is not responsible for the privacy or security practices of our customers, which may differ from those set forth in this privacy statement.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>SWIS App account</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">With a SWIS App account, you can sign in to the SWIS. Personal data associated with your SWIS App account includes credentials, name and contact data, device and usage data, your contacts, information about your activities, and your interests and favorites/bookmarks. Signing in to your SWIS App account enables personalization and consistent experiences across products and devices.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you sign into a service offered by a third party with your SWIS App account, you will share with that third party the account data required by that service.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Other important privacy information</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Below you will find additional privacy information, such as how we secure your data, where we process your data, and how long we retain your data. </span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Search and artificial intelligence</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Search and artificial intelligence products connect you with information and intelligently sense, process, and act on information&mdash;learning and adapting over time.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; background-color: #ffffff;\"><span style=\"font-size: 19.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Entertainment and related services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Entertainment and Related Services power rich experiences and enable you to access a variety of content, applications and games.</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 9.4pt; background-color: #ffffff;\">&nbsp;</p>";

        $terms = "<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS Terms &amp; Conditions</span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Last Updated: April 2019</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Welcome to SWIS App</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Thanks for using our products and services (&ldquo;Services&rdquo;). The Services are provided by HardSpro LLC dba SWIS App (&ldquo;SWIS App&rdquo;), located at 6 Tularosa Ct. Aliso Viejo, CA 92656, United States.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">By using our Services, you are agreeing to these terms. Please read them carefully.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Our Services are very diverse, so sometimes additional terms or product requirements (including age requirements) may apply. Additional terms will be available with the relevant Services, and those additional terms become part of your agreement with us if you use those Services.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Using our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You must follow any policies made available to you within the Services.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Don&rsquo;t misuse our Services. For example, don&rsquo;t interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. You may use our Services only as permitted by law, including applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Don&rsquo;t remove, obscure, or alter any legal notices displayed in or along with our Services.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Our Services display some content that is not SWIS App&rsquo;s. This content is the sole responsibility of the entity that makes it available. We may review content to determine whether it is illegal or violates our policies, and we may remove or refuse to display content that we reasonably believe violates our policies or the law. But that does not necessarily mean that we review content, so please don&rsquo;t assume that we do.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">In connection with your use of the Services, we may send you service announcements, administrative messages, and other information. You may opt out of some of those communications.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Our Services are available on mobile devices. Do not use such Services in a way that distracts you and prevents you from obeying traffic or safety laws.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Your SWIS App Account</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You may need an email account in order to use some of our Services. If you are using a an email account assigned to you by an administrator, different or additional terms may apply and your administrator may be able to access or disable your account.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">To protect your SWIS App Account, keep your password confidential. You are responsible for the activity that happens on or through your SWIS App Account. Try not to reuse your SWIS App Account password on third-party applications. If you learn of any unauthorized use of your password or SWIS App Account, please contact us immediately. &nbsp;</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Privacy and Copyright Protection</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App&rsquo;s privacy policy explains how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that SWIS App can use such data in accordance with our privacy policies.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We respond to notices of alleged copyright infringement and terminate accounts of repeat infringers according to the process set out in the U.S. Digital Millennium Copyright Act.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We provide information to help copyright holders manage their intellectual property online. If you think somebody is violating your copyrights and want to notify us, you can find information about submitting notices and SWIS App&rsquo;s policy about responding to notices&nbsp;</span><span style=\"font-size: 12pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">in our help center or contact us.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Your Content in our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">When you upload, submit, store, send or receive content to or through our Services, you give SWIS App (and those we work with) a worldwide license to use, host, store, reproduce, modify, create derivative works (such as those resulting from translations, adaptations or other changes we make so that your content works better with our Services), communicate, publish, publicly perform, publicly display and distribute such content. The rights you grant in this license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones. This license continues even if you stop using our Services (for example, for a business listing you have added to SWIS App). Some Services may offer you ways to access and remove content that has been provided to that Service. Also, in some of our Services, there are terms or settings that narrow the scope of our use of the content submitted in those Services. Make sure you have the necessary rights to grant us this license for any content that you submit to our Services.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Our automated systems analyze your content (including emails) to provide you personally relevant product features, such as customized search results, tailored advertising, and spam and malware detection. This analysis occurs as the content is sent, received, and when it is stored.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you have a SWIS App Account, we may display your Profile name, Profile photo, and actions you take on SWIS App or on third-party applications connected to your SWIS App Account (such as +1&rsquo;s, reviews you write and comments you posts) in our Services, including displaying in ads and other commercial contexts. We will respect the choices you make to limit sharing or visibility settings in your SWIS App Account. </span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You can find more information about how SWIS App uses and stores content in the privacy policy or additional terms for particular Services. If you submit feedback or suggestions about our Services, we may use your feedback or suggestions without obligation to you.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>About Software in our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">When a Service requires or includes downloadable software, this software may update automatically on your device once a new version or feature is available. Some Services may let you adjust your automatic update settings.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SWIS App gives you a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use the software provided to you by SWIS App as part of the Services. This license is for the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by SWIS App, in the manner permitted by these terms. You may not copy, modify, distribute, sell, or lease any part of our Services or included software, nor may you reverse engineer or attempt to extract the source code of that software, unless laws prohibit those restrictions or you have our written permission.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Open source software is important to us. Some software used in our Services may be offered under an open source license that we will make available to you. There may be provisions in the open source license that expressly override some of these terms.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Modifying and Terminating our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We are constantly changing and improving our Services. We may add or remove functionalities or features, and we may suspend or stop a Service altogether.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">You can stop using our Services at any time, although we&rsquo;ll be sorry to see you go. SWIS App may also stop providing Services to you, or add or create new limits to our Services at any time.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We believe that you own your data and preserving your access to such data is important. If we discontinue a Service, where reasonably possible, we will give you reasonable advance notice and a chance to get information out of that Service.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Our Warranties and Disclaimers</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We provide our Services using a commercially reasonable level of skill and care and we hope that you will enjoy using them. But there are certain things that we don&rsquo;t promise about our Services.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS OR ADDITIONAL TERMS, NEITHER SWIS APP NOR ITS SUPPLIERS OR DISTRIBUTORS MAKE ANY SPECIFIC PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON&rsquo;T MAKE ANY COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC FUNCTIONS OF THE SERVICES, OR THEIR RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS. WE PROVIDE THE SERVICES &ldquo;AS IS&rdquo;.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Liability for our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">WHEN PERMITTED BY LAW, SWIS APP, AND SWIS APP&rsquo;S SUPPLIERS AND DISTRIBUTORS, WILL NOT BE RESPONSIBLE FOR LOST PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF SWIS APP, AND ITS SUPPLIERS AND DISTRIBUTORS, FOR ANY CLAIMS UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE AMOUNT YOU PAID US TO USE THE SERVICES (OR, IF WE CHOOSE, TO SUPPLYING YOU THE SERVICES AGAIN).</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">IN ALL CASES, SWIS APP, AND ITS SUPPLIERS AND DISTRIBUTORS, WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT IS NOT REASONABLY FORESEEABLE.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>Business uses of our Services</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you are using our Services on behalf of a business, that business accepts these terms. It will hold harmless and indemnify SWIS App and its affiliates, officers, agents, and employees from any claim, suit or action arising from or related to the use of the Services or violation of these terms, including any liability or expense arising from claims, losses, damages, suits, judgments, litigation costs and attorneys&rsquo; fees.</span></p>
<p>&nbsp;</p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;\"><span style=\"font-size: 18pt;  color: #3c4043; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\"><b>About these Terms</b></span></p>
<p style=\"line-height: 1.2; margin-top: 0pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We may modify these terms or any additional terms that apply to a Service to, for example, reflect changes to the law or changes to our Services. You should look at the terms regularly. We&rsquo;ll posts notice of modifications to these terms on this page. We&rsquo;ll posts notice of modified additional terms in the applicable Service. Changes will not apply retroactively and will become effective no sooner than fourteen days after they are posted. However, changes addressing new functions for a Service or changes made for legal reasons will be effective immediately. If you do not agree to the modified terms for a Service, you should discontinue your use of that Service.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If there is a conflict between these terms and the additional terms, the additional terms will control for that conflict.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">These terms control the relationship between SWIS App and you. They do not create any third party beneficiary rights.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If you do not comply with these terms, and we don&rsquo;t take action right away, this doesn&rsquo;t mean that we are giving up any rights that we may have (such as taking action in the future).</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">If it turns out that a particular term is not enforceable, this will not affect any other terms.</span></p>
<p style=\"line-height: 1.2; margin-top: 7.5pt; margin-bottom: 7.5pt;\"><span style=\"font-size: 10.5pt;  color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">The laws of California, U.S.A., excluding California&rsquo;s conflict of laws rules, will apply to any disputes arising out of or relating to these terms or the Services. All claims arising out of or relating to these terms or the Services will be litigated exclusively in the federal or state courts of Orange County, California, USA, and you and SWIS App consent to personal jurisdiction in those courts.</span></p>";


        $about = "<p><span style=\"font-weight: 400;font-size: 10.5pt;\">SWIS stands for (See What I Search).&nbsp; It is a place to share what you search, and to connect with others to see what they search.&nbsp; Giving everyone insight into how they learn, catch early trends, plan vacations, weddings, purchase homes, cars and much more.&nbsp; Through this type of transparency, we will empower ourselves and revolutionize the future of search.</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">SWIS is the brainchild of Sam Bruni, an early tech pioneer who helped build and grow multiple startups starting in the late 90&rsquo;s.&nbsp; This included Ancestry.com, where he helped take it from a small startup, to an over 100 million dollar business in just a few short years.</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">The idea of SWIS came about in the early 2000&rsquo;s.&nbsp; As search engines started to become more popular, Sam realized that they know everything about us, specifically the things that were happening around us.&nbsp;&nbsp;</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">One sleepless night, he thought about how if a pandemic were to breakout, people would search for the symptoms they were experiencing, and as more people searched those same symptoms in a highly concentrated area, the search engines would know what was about to breakout in that location.&nbsp; We personally do not have this information, and he believed we should.&nbsp;</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">The SWIS concept grew from there, as he realized we don&rsquo;t know where the smartest people go to learn, or simple things like concerts and festival that are going to take place, especially in areas you don&rsquo;t live. What an advantage we would all have if we were more willing to share our search journey with others.</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">In 2018, Sam finally felt the time was right, so here we are, a small startup, finally getting off the ground.&nbsp; It is our hope that you will help make SWIS great by simply just searching.</span></p>
<p>&nbsp;</p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">Sincerely,</span></p>
<p><span style=\"font-weight: 400;font-size: 10.5pt;\">The SWIS Team</span></p>";
        $faq = '<strong style="font-size: 14pt;">SWIS App FAQ</strong>
<br/><br/>
<span style="font-size: 12pt;">
<strong >Question</strong><span style="font-weight: 400;">: What is SWIS?</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: SWIS allows you to connect with your friends, family and others to let them see what you search.&nbsp; SWIS stands for See What I Search.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: How do I use SWIS?</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: SWIS is easy to use. You click on the search icon located at the bottom of the app located in the middle of the apps footer. This will take you to a search page where you can search the internet. Each webpage, video, image and url that you click on is then tracked and shows up on your followers Home/Feed Page.&nbsp; I emphasize you must click, so if you do a search but don&rsquo;t click on a result, it will not get tracked. While you are in the search section of the app, everything you click on is saved and compiled into what we call a &ldquo;search journey&rdquo;. To end a &ldquo;search journey&rdquo; leave the search section of the app by going back to the Home/Feed page of the app.&nbsp;</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: Can I edit a &ldquo;search journey&rdquo;?</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: yes, you can delete all or parts of a search journey by going to your profile page and clicking on the three editing dots on the right side of a search result just under the search image.&nbsp; There you will see the option to delete just the one search journey you are currently viewing, or the entire search journey.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: Can I hide what I&rsquo;m searching?</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: Yes, not every search has to be shown. If you want to turn off sharing your searches with your followers, go to the settings menu, and in the menu you will see the green toggle for &ldquo;share searches&rdquo; is on (green is on).&nbsp; You can turn this off by sliding the toggle to the left so that the green is not showing. Note, after your first time registering on the app, the default is set to on. All of your searches will show up in your networks home feed.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: What does &ldquo;Share Searches Locally&rdquo; mean?&nbsp;&nbsp;</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: SWIS has a unique feature which allows you to show your searches to people near you whether or not they are following you.&nbsp; Currently, &ldquo;share searches locally&rdquo; is sharing within a 50-mile radius of where you are located while using the app. You can turn this feature off by going to the settings menu, and in the drop down, turn the &ldquo;share searches locally&rdquo; toggle to the left so that the green is not showing.&nbsp; When the green is showing, this means you are sharing. After your first time registering on the app, the default is set to on. To see local searches you must click on the Local Search icon at the bottom of the app located in the footer.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: How can I go private?&nbsp;</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: You can go private by going to the settings menu and clicking on the edit profile.&nbsp; Once you are on the edit profile menu, you will see two toggles switches, one is called &ldquo;share searched&rdquo;, and the other is called &ldquo;share bookmarks&rdquo;.&nbsp; These options are both set to on when the toggle switch is green. You can stop sharing one, or the other, or both with the toggle switches. Keep in mind though, that when you have these turned off, they will only be hidden from non-followers.&nbsp; Your followers will always be able to see them.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: What does &ldquo;Auto Accept Follows&rdquo; mean?</span> <span style="font-weight: 400;">&nbsp;&nbsp;</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: This works just like it states.&nbsp; When it is turned on, this allows you to not have to accept each follow request manually.&nbsp; If you are not trying to be selective about who is following you, you can leave this feature on. When the green is showing on the toggle, this means your follow requests are automatically accepted.&nbsp; If the toggle switch is set to off, then you will need to manually accept your followers. Default after registration is set to auto accept followers.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: How to accept follow requests?</span><br />
<strong>Answer</strong><span style="font-weight: 400;">: Go to the settings menu and then to edit profile.&nbsp; In the edit profile screen, you will see &ldquo;Follow Requests&rdquo; at the bottom of the menu and a number indicating how many pending follow requests you have.&nbsp; You can click on this to manually select who you want to let follow you. Note, that manual follow requests= only works if your &ldquo;Auto Accept Follows&rdquo; is turned off.</span>
<br/><br/>
<strong>Question</strong><span style="font-weight: 400;">: How do I manage notifications?&nbsp;&nbsp;</span><br/>
<strong>Answer</strong><span style="font-weight: 400;">:&nbsp; Go to the settings menu and then to notifications feature in the menu.&nbsp; In the notification&rsquo;s menu, you can choose to be notified when somebody likes one of your searches, comments on one of your searches, or starts following you.&nbsp; After registration, these are automatically set to on, meaning the green toggle is showing. To turn notifications off, please slide the toggle to the left so that no green is showing.</span>
<br/><br/></span>';

        $data = "";
        switch ($type){
            case "privacy":
                $data = $privacy;
                break;
            case "term":
                $data = $terms;
                break;
            case "about":
                $data = $about;
                break;
            case "faq":
                $data = $faq;
                break;
        }
        return response([
            'responseCode' => 200,
            'responseMessage' => "",
            'data' => $data
        ],200);
    }

    public function settings(){
        return response([
            'responseCode' => 200,
            'responseMessage' => "",
            'settings' => Setting::all()
        ],200);
    }
}
